name: Assemble

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

  build:
    runs-on: ubuntu-latest
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


